CREATE DATABASE projet_mai26;
USE projet_mai26;

CREATE TABLE IF NOT EXISTS `users` (
id_user INT PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(100) NOT NULL UNIQUE,
`password` VARCHAR (255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);